stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
    - ./data/bronze/tennis_atp/atp_matches_2015.csv
    - ./data/bronze/tennis_atp/atp_matches_2016.csv
    - ./data/bronze/tennis_atp/atp_matches_2017.csv
    - ./data/bronze/tennis_atp/atp_matches_2018.csv
    - ./data/bronze/tennis_atp/atp_matches_2019.csv
    - ./data/bronze/tennis_atp/atp_matches_2020.csv
    - ./data/bronze/tennis_atp/atp_matches_2021.csv
    - ./data/bronze/tennis_atp/atp_matches_2022.csv
    - ./data/bronze/tennis_atp/atp_matches_2023.csv
    - ./data/bronze/tennis_odds/2015.xlsx
    - ./data/bronze/tennis_odds/2016.xlsx
    - ./data/bronze/tennis_odds/2017.xlsx
    - ./data/bronze/tennis_odds/2018.xlsx
    - ./data/bronze/tennis_odds/2019.xlsx
    - ./data/bronze/tennis_odds/2020.xlsx
    - ./data/bronze/tennis_odds/2021.xlsx
    - ./data/bronze/tennis_odds/2022.xlsx
    - ./data/bronze/tennis_odds/2023.xlsx
    - src/data/preprocess.py
    outs:
    - ./data/silver/train.csv
    - ./data/silver/test.csv
